import type { ExtendedVitals } from './types';

export interface VitalsScenario {
  id: string;
  name: string;
  description: string;
  vitals: ExtendedVitals;
  expectedAnomaly: boolean;
}

export const SCENARIOS: VitalsScenario[] = [
  {
    id: 'normal-resting',
    name: 'Normal Resting',
    description: 'Healthy baseline vitals while at rest',
    vitals: {
      heart_rate: 72,
      blood_oxygen: 98,
      blood_pressure_systolic: 120,
      blood_pressure_diastolic: 80,
      glucose_level: 95,
      body_temperature: 98.6,
      respiratory_rate: 16,
      activity_level: 0.1,
      sleep_quality: 0.8,
      stress_level: 0.2,
      hrv_sdnn: 50,
      steps_count: 100,
      calories_burned: 50,
    },
    expectedAnomaly: false,
  },
  {
    id: 'normal-active',
    name: 'Normal Active',
    description: 'Elevated vitals during moderate physical activity',
    vitals: {
      heart_rate: 95,
      blood_oxygen: 97,
      blood_pressure_systolic: 130,
      blood_pressure_diastolic: 85,
      glucose_level: 110,
      body_temperature: 99.0,
      respiratory_rate: 20,
      activity_level: 0.7,
      sleep_quality: 0.6,
      stress_level: 0.3,
      hrv_sdnn: 45,
      steps_count: 5000,
      calories_burned: 350,
    },
    expectedAnomaly: false,
  },
  {
    id: 'post-stroke-recovery',
    name: 'Post-Stroke Recovery',
    description: 'Elevated BP and stress, low activity during rehab',
    vitals: {
      heart_rate: 80,
      blood_oxygen: 96,
      blood_pressure_systolic: 145,
      blood_pressure_diastolic: 95,
      glucose_level: 105,
      body_temperature: 98.4,
      respiratory_rate: 18,
      activity_level: 0.1,
      sleep_quality: 0.4,
      stress_level: 0.7,
      hrv_sdnn: 35,
      steps_count: 200,
      calories_burned: 80,
    },
    expectedAnomaly: true,
  },
  {
    id: 'copd-exacerbation',
    name: 'COPD Exacerbation',
    description: 'Low oxygen, high respiratory rate, elevated heart rate',
    vitals: {
      heart_rate: 110,
      blood_oxygen: 88,
      blood_pressure_systolic: 135,
      blood_pressure_diastolic: 85,
      glucose_level: 100,
      body_temperature: 99.2,
      respiratory_rate: 28,
      activity_level: 0.05,
      sleep_quality: 0.3,
      stress_level: 0.8,
      hrv_sdnn: 30,
      steps_count: 50,
      calories_burned: 80,
    },
    expectedAnomaly: true,
  },
  {
    id: 'hypoglycemia',
    name: 'Hypoglycemia',
    description: 'Low glucose with compensatory heart rate and stress',
    vitals: {
      heart_rate: 100,
      blood_oxygen: 97,
      blood_pressure_systolic: 115,
      blood_pressure_diastolic: 75,
      glucose_level: 55,
      body_temperature: 97.8,
      respiratory_rate: 18,
      activity_level: 0.2,
      sleep_quality: 0.5,
      stress_level: 0.6,
      hrv_sdnn: 40,
      steps_count: 300,
      calories_burned: 120,
    },
    expectedAnomaly: true,
  },
  {
    id: 'fever-infection',
    name: 'Fever / Infection',
    description: 'High temperature with elevated heart rate and low activity',
    vitals: {
      heart_rate: 95,
      blood_oxygen: 96,
      blood_pressure_systolic: 110,
      blood_pressure_diastolic: 70,
      glucose_level: 120,
      body_temperature: 101.5,
      respiratory_rate: 22,
      activity_level: 0.05,
      sleep_quality: 0.3,
      stress_level: 0.5,
      hrv_sdnn: 38,
      steps_count: 80,
      calories_burned: 200,
    },
    expectedAnomaly: true,
  },
  {
    id: 'hypertensive-crisis',
    name: 'Hypertensive Crisis',
    description: 'Dangerously high blood pressure with high stress',
    vitals: {
      heart_rate: 105,
      blood_oxygen: 97,
      blood_pressure_systolic: 180,
      blood_pressure_diastolic: 120,
      glucose_level: 130,
      body_temperature: 98.8,
      respiratory_rate: 20,
      activity_level: 0.1,
      sleep_quality: 0.2,
      stress_level: 0.9,
      hrv_sdnn: 25,
      steps_count: 50,
      calories_burned: 90,
    },
    expectedAnomaly: true,
  },
  {
    id: 'sleep-window',
    name: 'Sleep Window',
    description: 'Low activity vitals during nighttime sleep',
    vitals: {
      heart_rate: 60,
      blood_oxygen: 97,
      blood_pressure_systolic: 110,
      blood_pressure_diastolic: 70,
      glucose_level: 85,
      body_temperature: 97.5,
      respiratory_rate: 14,
      activity_level: 0.02,
      sleep_quality: 0.9,
      stress_level: 0.1,
      hrv_sdnn: 55,
      steps_count: 0,
      calories_burned: 40,
    },
    expectedAnomaly: false,
  },
];
