import { ContextCode, MedicationWatchCode, ObservationCode } from "./uc4Types";

export const OBSERVATION_CODES: ObservationCode[] = [
  "LOOKS_NORMAL",
  "NOT_SURE",
  "DEVICE_OR_SENSOR_ISSUE",
  "RECENT_ACTIVITY_OR_EXERTION",
  "LOW_MOVEMENT",
  "TRANSFER_OR_POSITIONING_CONTEXT",
  "PAIN_OR_DISCOMFORT",
  "UNUSUAL_FATIGUE",
  "POOR_SLEEP_OR_RESTLESSNESS",
  "BREATHING_CONCERN",
  "COLOR_OR_OXYGEN_CONCERN",
  "MISSED_OR_DELAYED_MEDICATION",
  "RECENT_MEDICATION_CHANGE",
  "APPETITE_OR_HYDRATION_CHANGE",
  "BOWEL_OR_BLADDER_CHANGE",
  "SKIN_OR_PRESSURE_CONCERN",
  "SEIZURE_LIKE_EVENT_REPORTED",
  "UNUSUAL_RESPONSIVENESS",
  "CAREGIVER_WANTS_PROVIDER_REVIEW",
  "FALL_OR_NEAR_FALL",
  "THERAPY_ROUTINE_DIFFICULTY",
];

export const CONTEXT_CODES: ContextCode[] = [
  "DURING_TRANSFER",
  "WHILE_SITTING_OR_POSITIONED",
  "AFTER_ACTIVITY_OR_THERAPY",
  "AROUND_MEDICATION_TIME",
  "DURING_SLEEP_OR_NIGHT",
  "MEAL_OR_HYDRATION_RELATED",
  "BATHROOM_OR_BOWEL_BLADDER",
  "UNKNOWN_OR_NOT_SURE",
];

export const MEDICATION_WATCH_CODES: MedicationWatchCode[] = [
  "SLEEPINESS_FATIGUE",
  "DIZZINESS_OR_LIGHTHEADEDNESS",
  "WEAKNESS_OR_LOW_TONE_CONCERN",
  "MOOD_BEHAVIOR_CHANGE",
  "APPETITE_OR_HYDRATION_CHANGE",
  "BOWEL_CHANGE",
  "BREATHING_CONCERN",
  "HEART_RATE_OR_BP_CONCERN",
  "SKIN_RASH_OR_ALLERGY_CONCERN",
  "MISSED_OR_DELAYED_DOSE",
  "MEDICATION_TIMING_CONTEXT_NEEDED",
];